server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: gov-uk-service

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

logging:
  level:
    root: INFO
    uk.gov.service: DEBUG 